# 图形验证码过期时间
REDIS_IMAGE_CODE_EXPIRED = 300
# 短信验证码过期时间
REDIS_SMS_CODE_EXPIRED = 300
# 容联云短信有效期
RONG_LIAN_EXPIRED = 300
# fastdfs文件存储
FDFS_BASE_URL = 'http://172.17.0.2:8888/'
# 详情页评论最大显示条数
HOUSE_DETAIL_COMMENT_DISPLAY_COUNTS = 30
# 最大登录次数
LOGIN_ERROR_MAX_TIMES = 5
# 登录次数时间限制
LOGIN_OUT_TIME_ALLOW_TIME = 300