# 图形验证码保存失败
IMAGE_CODE_SAVE_REDIS_FAIL = 400
# 数据不完整
INCOMPLETE_DATA = 401
# 图形验证码过期
IMAGE_CODE_EXPIRED = 402
# 图形验证码错误
IMAGE_CODE_ERROR = 403
# 数据库链接错误
MYSQL_CONNECTION_ERROR = 404
# redis链接错误
REDIS_CONNECTION_ERROR = 405
# 数据已存在
DATA_EXISTS = 406
# 数据错误
DATA_ERROR = 407
# 登录次数受限了
LOGIN_MAX_TIMES_ERROR = 408
# session错误
SESSION_ERROR = 409
# 数据不存在
DATA_UN_EXISTS = 410
# 成功
OK = 1